import "./globals.css";
import { Inter } from "next/font/google";
import Headers from "@/components/Headers";
import Footer from "@/components/Footer";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="dark">
        <Headers />
        {children}
        <ToastContainer />
      </body>
    </html>
  );
}
